[tool.isort]
line_length = 100
multi_line_output = 3
known_first_party = "tourniquet"
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


[tool.black]
line-length = 100
