name: CI

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: docker build -t tourniquet .

  tests-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        llvm-version: [9, 10, 11]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: llvm deps
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${{ matrix.llvm-version }} main"
          sudo apt update
          sudo apt install \
            llvm-${{ matrix.llvm-version }} \
            llvm-${{ matrix.llvm-version }}-dev \
            clang-${{ matrix.llvm-version }} \
            libclang-${{ matrix.llvm-version }}-dev

      - name: lint
        run: make lint

      - name: typecheck
        run: make typecheck

      - name: test
        run: |
          export LLVM_DIR=/usr/lib/llvm-${{ matrix.llvm-version }}/lib/cmake/llvm
          export Clang_DIR=/usr/lib/llvm-${{ matrix.llvm-version }}/lib/cmake/clang
          make test

  tests-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        llvm-version: [9]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: system deps
        run: brew install llvm@${{ matrix.llvm-version }}

      - name: python deps
        run: make dev

      - name: build
        run: make build

      - name: test
        run: make test
